### PR TITLE
fix(profile, dev server): fix bug in dev server configuration and add back profile

### LINKED ISSUE #286: Add back profile icon on sidebar
Currently, there is no way to view your own profile (unless you go to `/[yourpeername]`, which, why would you know to do that?)

Let's add back the profile icon, and also the option to set your poster and profile photo.

### LINKED ISSUE #287: Bug - Because of dev server configuration, browserHistory does not work on dev server
This is fixed by configuring the devServer in webpack:

```
devServer: {
    historyApiFallback: true
}
```

### PR DESCRIPTION
**Pull request by ramfox**
closes #287
closes #286

### CODE REVIEW

File: lib/components/App.js [hunk 1]
```diff
@@ -39,7 +39,6 @@ export default class App extends Base {
         }
         this.props.pingApi()
         iter++
-        console.log(iter)
```
Comment (b5) [inline lib/components/App.js:42]: 😄

**Review by b5 — APPROVED** [review]
solid, like the switch to `selectSessionProfileID`.

🇲🇳 🇲🇭 🇲🇴

File: lib/components/App.js (hunk 1 above)
Comment (ramfox) [reply lib/components/App.js:42]: 😅
