### PR TITLE
refactor(*): fixing minor bugs

### LINKED ISSUE #387: Adjustments to welcome page
1) link to our github and our help docs, rather then just mentioning our github
2) a place where folks can change their repo name, since we know this is the first time they are opening the app.

### LINKED ISSUE #413: bug: dataset body editor, should be able to click away and have changes still save
Right now, only clicking `Enter` when editing a field keeps the change.

### LINKED ISSUE #415: Confirmation Flag / Warning on Removing Dataset
When I click into a version of a dataset that I would like to delete, Qri deletes all previous versions without confirming. Would like to have a message prior to action: 'This action removes all versions of this dataset from qri. Are you sure you want to remove?"  [Yes ] [No] buttons.

### LINKED ISSUE #416: 0.6.0 minor issues punchlist part 2
~Editor => contrast is a little low when blue is over grey~ punt/let's do this when we have more time to think about what exactly should change.
* [x] Dataset Body component => should be no edit
 * [x] Editor => Body => 
  when editing a field, clicking away doesn't save the contents of the field, only pushing `Enter` does #413
  * okay so on further investigation, it looks like what is really happening is the FIRST time you try to edit a field, and click away or press enter or give any indication that you are done with that field, the `this.body` that exist in the `onAfterChange` function (which then gets passed to `onChangeBody` that sets the body in the reducer) is not the body with the appropriate changes. Every other time, after the first time, the body at `this.body` is correct
* [x] Remove warning => remind people they are removing the entire dataset, not just the latest version #415 
* [x] Welcome => redesign #387 
* [x] Welcome => ToS exit error #403 
* [x] Peername => create peername page
* [x] fix #419

### LINKED ISSUE #419: js errors running `yarn web:dev` at master
Pulled a new clone of this repo, then running `yarn web:dev` gives me the following stacktrace:

```
Collection.js:75

Uncaught TypeError: Cannot read property 'value' of undefined
    at ProxyComponent.template (Collection.js:75)
    at ProxyComponent.template (react-hot-loader.development.js:580)
    at ProxyComponent.render (Base.js:63)
    at ProxyComponent.hotComponentRender (react-hot-loader.development.js:620)
    at ProxyComponent.proxiedRender (react-hot-loader.development.js:635)
    at finishClassComponent (react-dom.development.js:13537)
    at updateClassComponent (react-dom.development.js:13500)
    at beginWork (react-dom.development.js:14089)
    at performUnitOfWork (react-dom.development.js:16415)
    at workLoop (react-dom.development.js:16453)
```

Followed by:
```
react-dom.development.js:14549

The above error occurred in the <Collection> component:
    in Collection (created by Route)
    in Route (created by withRouter(Collection))
    in withRouter(Collection) (created by Connect(withRouter(Collection)))
    in Connect(withRouter(Collection)) (created by Route)
    in Route (created by Component)
    in Switch (created by Component)
    in div (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Component)
    in Component (created by Root)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Connect(ConnectedRouter))
    in Connect(ConnectedRouter) (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

Reseting to ce498e1592 (release 0.6.0) doesn't display this error.

### PR DESCRIPTION
**Pull request by ramfox**
closes #416 
closes #413 
closes #415 
closes #419 
closes #387

### CODE REVIEW

**Comment by b5** [comment]
daaaaaaaamn I'm like so pumped to review dis

File: lib/reducers/app.js [hunk 1]
```diff
@@ -26,14 +28,18 @@ const initialState = {
   message: '',
   viewMode: 'dataset',
   location: '',
-  acceptedTOS: !!store().getItem(acceptedTOSKey)
+  acceptedTOS: !!store().getItem(acceptedTOSKey),
```
Comment (b5) [inline lib/reducers/app.js:31]: In later PRs we should consider refactoring `acceptedTOS` and `hasSetPeername` into a single "onboarding" value that tracks onboarding state as an explicit flow from one state to the next. Not a high-enough priority at this point tho.

File: lib/reducers/editor.js [hunk 2]
```diff
@@ -60,9 +63,14 @@ export default function editorReducer (state = initialState, action) {
       return Object.assign({}, state, { dirty: true,
         dataset: Object.assign({}, state.dataset, { viz: action.viz })
       })
-
     case EDITOR_SET_BODY:
       return Object.assign({}, state, { dirty: true, body: action.body })
+    case EDITOR_UPDATE_BODY:
```
Comment (b5) [inline lib/reducers/editor.js:68]: Totally fine for now, long term I'd like to merge `EDITOR_UPDATE_BODY` into `EDITOR_SET_BODY`. Not worried about it now tho

File: lib/components/editor/EditBody.js [hunk 3]
```diff
@@ -44,34 +29,22 @@ export default class EditBody extends Base {
 
   onAddBody () {
     // TODO - check structure & produce proper data format
-    this.props.onChangeBody([['', ''], ['', '']])
+    this.props.onSetBody([['', ''], ['', '']])
```
Comment (b5) [inline lib/components/editor/EditBody.js:32]: Muuuuuuuuch nicer. Good TODO as well. Hopefully we can tackle this properly when we take on #418

File: lib/components/dataset/Dataset.js [hunk 4]
```diff
@@ -104,17 +106,26 @@ export default class Dataset extends Base {
...
 
-  handleDeleteDataset () {
-    const { datasetRef } = this.props
-    return () => {
-      if (confirm('are you sure you want to remove this dataset from your qri node? (Note: if this dataset has been added by other peers, the data may still exist on the network)')) {
-        this.props.deleteDataset(datasetRef).then((action) => {
-          this.props.history.push('/')
-        })
-      }
+  modal (name, data = {}) {
```
Comment (b5) [inline lib/components/dataset/Dataset.js:109]: much nicer than our `confirm` from before. Solid work on the delete modal

**Review by b5 — APPROVED** [review]
Ok a few comments that I'm intending for later. Let's merge this and tackle issues I've outlined here in subsequent PRs
