### PR TITLE
fix(Editor): fixing bugs and making changes to the editor to make it more usable

### LINKED ISSUE #435: fix(editor): fix bugs that get in the way of using qri
* [x] removing "body" doesn't work
* [x] saving tabular/csv data removes a row each time you save (#436)
* [x] can't save a viz for some reason
* [x] allow removal of schema (if schema section is empty/deleted), don't add a schema by default.
* [x] row #s too dark in edit mode
* [x] tf print statements don't show up 

Punting on these issues:
* can't recall a tf on the frontend
* dataset name show at top in editor
* if on meta page, and you click edit, you should be directed to the meta page on the editor
* editor should return you to where you left off if you navigate away

### PR DESCRIPTION
**Pull request by ramfox**
closes #435 

Also fixed bug where user's preference for column and row order did not stay when you navigated away from the edit body page and back.

### CODE REVIEW

**Comment by ramfox** [comment]
@b5 There are two errors which I outline briefly in the commit message.

> - `afterCreateCol`/`createColumnHeader` is erroring, which seems to be a bug with `createColumnHeader`, specifically with calling the `setSchema` action. I believe it is a bug because all three new functions use the `this.props.setSchema`, and `afterCreateCol` is the only one the is erroring. Also, this issue: handsontable/handsontable#4043

This isn't breaking anything, there is just an annoying error popping up. This second error is the one that has me frustrated:

> - The `afterColumnMove` event/`moveColumnHeaders` function that it calls -> The functions are properly changing the schema. We are getting the correct array of columnHeaders down at the component, but for some reason the table will only display the previous props, never the current one.

So when  you move a column (or columns), it either looks like nothing has happened or the column headers shift around in a weird order. The `columnHeaders` array that get passed down to the component is in the correct order, however (as you can see from logging). And if you switch to the structure view and back to the body view, the columns move to the correct order

**Comment by ramfox** [comment]
OhhI figured out the problem!!!!

HandsonTable is also tracking out the columns change, and move the column headers accordingly. But I'm also changing what we pass to handsontable! So the array is changing, but handsontable is keeping track of those changes, so each switch is happening twice.

Going to have to think about this, because we definitely need to keep track of this on the schema side, especially since any data that is sent over is sent over in the order that we see in the editor (I believe). I'll have to think about what we need to keep track of, and where it should be kept.

**Comment by ramfox** [comment]
Okay, so after all that... got the correct algos and structures to get the columns headers to be persistent and accurate, even when you navigate away from the page and come back.

However! We actually don't have the same feature happening with our data: if you move a column or row, navigate away and then back, these changes don't keep. So I've commented out the part that keeps the column headers persistent (so they match the underlying data). But! This has been really educational, since now I've spent so much time figuring out how handsontable keeps track of changes without manipulating the underlying data, I have a better idea of how we might be able to do the same. 

Also we now have a blueprint to get persistent data display when we navigate from the page and back, by following the pattern in `moveColumnsHeaders`/`setReOrder`, however, pretty sure it wouldn't be the most optimal way. But might be good for now. Anyway, not tackling that in this pr!

**Comment by ramfox** [comment]
OMG so pumped. Okay so while getting ready for bed this idea of tracking changes/order rather than the actually data itself was running through my head and I figured out a way to get the column  (and row!) changes to be persistent.

Basically, using the same idea that I was initially working with:

There is no reason to have the schema or body tracked in local state if we are instead tracking the changes/swaps/additions in row and column #. So instead, we have two arrays, one tracking the columns and one tracking the rows. Each index is the original location of the row or column and the value is the current position. 

Whenever we un-mount (or when we need to save), we collapse all the column and row changes and set the body or schema.

So fun! I'm sure there are bugs and there are def ways to make everything go faster, but it'd be great to get people to play around with it!

File: lib/components/form/ValidCheck.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
+import React from 'react'
+import PropTypes from 'prop-types'
+
+import Base from '../Base'
+
+export default class ValidCheck extends Base {
```
Comment (b5) [inline lib/components/form/ValidCheck.js:6]: Is this component being used anywhere?

File: lib/reducers/editor.js [hunk 2]
```diff
@@ -64,6 +96,65 @@ export default function editorReducer (state = initialState, action) {
...
+        })
+      }
+
+      if (action.schema.constructor === String) {
+        schemaString = action.schema
+        // if the schema is a string !== "":
+        // otherwise, parse the schema string
+        // if it can be parsed, set parsable to true
+        // add the parsedSchema to dataset.structure
+        try {
```
Comment (b5) [inline lib/reducers/editor.js]: having a `try` statement in a reducer that's being called on every keystroke in some situations is a bit dangerous.

File: lib/reducers/editor.js [hunk 3]
```diff
@@ -21,22 +23,52 @@ const initialState = {
   dataset: {},
   vizScript: undefined,
   transformScript: undefined,
-  body: undefined
+  body: undefined,
+  stringified: {
```
Comment (b5) [inline lib/reducers/editor.js]: This stringified stuff makes me uneasy. Lots of copying going on here, potentially of very large amounts of data. The schema is less concerning, but we can't be making multiple copies of the body on each keystroke.

For this to land, we need to keep **one** copy of the currently editing body in the reducer, and have that property be either a string or a parsed object. We only need to know if the body is 'parsable' when switching the bodyView property, which means we can handle the conversion in the `EDITOR_SET_BODY_VIEW` event. If conversion from string to object fails b/c the string isn't valid JSON we should set a new property on this reducer `bodyError`. and pass it along to the container. The BodyEditor component should check If `bodyError` is a truthy value, and display that instead of the table.

**Review by b5 — CHANGES_REQUESTED** [review]
Biggest thing that needs addressing is having only one copy of `body` in the editor reducer and being smart about events to handle how to interpret that body value. Once we land that I think we can merge this & set to refactoring

File: lib/components/form/ValidCheck.js (hunk 1 above)
Comment (ramfox) [reply lib/components/form/ValidCheck.js:6]: No, it was hold over from when I made a toggling between having and not having a header row. I assume it (or a version of it) will be used when we add uploading a file (because they will need to tell us if the csv file they are uploading has a header row) But happy to remove it for now, since it exists in a commit.

File: lib/reducers/editor.js (hunk 2 above)
Comment (ramfox) [reply lib/reducers/editor.js]: yes this was boneheaded, changing it :)

File: lib/reducers/editor.js (hunk 3 above)
Comment (ramfox) [reply lib/reducers/editor.js]: sounds good!

File: lib/actions/editor.js [hunk 4]
```diff
@@ -26,7 +31,7 @@ const blankDataset = {}
 
 // initDataset resets the editor to a blank dataset
 // TODO - consider renaming this to like "initEditor" or something to avoid confusion with "newDataset", "saveDataset" actions
-export function initDataset (name = '', dataset = blankDataset, transformScript = '', vizScript = '', body = '') {
+export function initDataset (name = '', dataset = blankDataset, transformScript = '', vizScript = '', body = undefined) {
```
Comment (b5) [inline lib/actions/editor.js:34]: No need for `body = undefined`, can be just `body`, which defaults to undefined

File: lib/actions/editor.js [hunk 5]
```diff
@@ -132,6 +137,16 @@ export function setStructure (structure = {}) {
   }
 }
 
+// setSchema updates/replaces the schema in
+// the dataset.structure section
+// as well as the the schema string section
```
Comment (b5) [inline lib/actions/editor.js:142]: remove:
`// as well as the the schema string section`

File: lib/reducers/editor.js [hunk 6]
```diff
@@ -21,22 +30,67 @@ const initialState = {
   dataset: {},
   vizScript: undefined,
   transformScript: undefined,
-  body: undefined
+  body: undefined,
+  colOrder: undefined,
```
Comment (b5) [inline lib/reducers/editor.js:34]: it's be great to get some comments explaining what each of these state properties is keeping track of, similar to the way we comment up go structs on the backend. It'll help later when we have to re-learn how we did all this stuff 😄

File: lib/utils/generate.js [hunk 7]
```diff
@@ -0,0 +1,191 @@
+import cloneDeep from 'clone-deep'
```
Comment (b5) [inline lib/utils/generate.js]: I can see how it took you a bunch of thinking to get this to work. I think you've secretly started into an implementation of Qri in javascript.

We should take this code more seriously than usual. Long term I think we'll move this into it's own package with tests & lots of architectural thinking, but. For this PR I'd like to see this file moved out of `util` and into a new directory: `lib/qri`. In follow up PRs we should start folding in tests.

**Review by b5 — APPROVED** [review]
NICE. Few small nits, and one big surprise new project. If you can ship these tiny changes LGTM.

File: lib/utils/generate.js (hunk 7 above)
Comment (ramfox) [reply lib/utils/generate.js]: v interesting. yep! making the change now

Comment (b5) [reply lib/utils/generate.js]: oh oh also, if you could add a comment to that file:
```
this file replicates some bare functionality of Qri in javascript for use on the frontend. 
We aren't actively building a full-featured Qri implementation, as the frontend needs 
new functionality previously reserved for Qri, we'll put it here.
```

**Comment by b5** [comment]
🎉 🌮 🎋
