### PR TITLE
fix(Editor): editor fixes and refactors

### LINKED ISSUE #407: bug: adding Transform Script in editor, and then removing it still passes to the backend that there should be a transform
My redux has failed and won't reboot, so I can't figure out exactly what's happening. But it looks like, even though the Transform file is `undefined`, the `dataset` file (that gets sent to the backend), still has some indication that there should be a transform attached to this save.

This causes errors when the backend then tries to open a transform file that doesn't exist.

### LINKED ISSUE #418: All dataset components in the editor must be nil by default and removable
This started off with the realization that because the frontend supplies a default schema, csv schema inference is broken. Because we can't remove/provide empty structure on frontend, there's no way to get the backend to do it's inference tricks.
 
The best way to fix this is to take the approach we use for `transform` and `viz` sections and apply it to _all_ dataset components. Now that we've gone through a bunch of work on refactoring the save path on the backend, this should be totally fine. As a concrete example, going to the editor and hitting `Reset` should remove all components, so clicking the `body` tab in the editor should initially show an `Add Body` button. Clicking `Add Body` should create the body component, make the editor visible, and place a "remove body" button on-screen.

While we're here, we should scrub through dataset editing actions to make sure removal actually removes the components. This should address #407. We _might_ need to do some work on the API to make sure nil components properly are properly parsed.

### LINKED ISSUE #423: bug(editor): changing from the json and csv body in structure errors
This only occurs if you make a change in the json before switching back to csv.

Changing the json sends back a stringified version of the body to the state tree. When you change from json to csv, the string version of the body gets passed to HotTable, and errors.

### PR DESCRIPTION
**Pull request by ramfox**
closes #418 
closes #407 
closes #423 

Frontend always assumes you are trying to send using json, unless otherwise specified in the structure. Which means that our schema inference won't ever happen unless we make the switch in the backend to infer a schema if no schema is found, and not just if no structure is found.

This is a bit of a stopgap as this assuming we are sending json part should really be happening on the backend, but if you do not send a schema or file extension then you cannot save a dataset right now.

### CODE REVIEW

File: lib/actions/editor.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ import {
   EDITOR_SET_BODY,
   EDITOR_UPDATE_BODY,
   EDITOR_SET_VIZ_SCRIPT,
-  EDITOR_SET_TRANSFORM_SCRIPT
+  EDITOR_SET_TRANSFORM_SCRIPT,
+  EDITOR_REMOVE_SECTION
```
Comment (b5) [inline lib/actions/editor.js:13]: Nice to see this pattern recognition & unification 😄

File: lib/actions/editor.js [hunk 2]
```diff
@@ -21,12 +22,7 @@ import { selectDatasetByPath } from '../selectors/dataset'
 import { selectCAFSString } from '../selectors/cafs'
 import { loadViz, loadTransform, loadDatasetBody } from './dataset'
 
-const blankDataset = {
-  structure: {
-    format: 'json',
-    schema: { type: 'array' }
-  }
-}
+const blankDataset = {}
```
Comment (b5) [inline lib/actions/editor.js:25]: looks like we can remove this constant entirely now

**Review by b5 — APPROVED** [review]
So good. Merge City
