### PR TITLE
Fixing bugs from dogfooding session

### LINKED ISSUE #118: Settings Page "Save" error message
Rico: on settings page, I made no changes, presed save and was shown a red/pink box saying: “error unmarshaling profile, unexpected end of json input”

### LINKED ISSUE #127: Recently run query at bottom of query list, not top
If you run a query and then check the 'history' tab, the query is at the bottom, not at the top like it should be.

Refreshing the page corrects the issue.

### LINKED ISSUE #133: Need loading spinner on addDataset

### LINKED ISSUE #134: Loading Spinner once 'load more' button is pushed

### LINKED ISSUE #135: Drag and drop doesn't trigger enable save button
Or possibly, should change to have clicking save button validate and show errors

### PR DESCRIPTION
**Pull request by ramfox**
closes #134 
closes #133 
closes #135 
closes #127
closes qri-io/qri#118

### CODE REVIEW

File: lib/selectors/pagination.js [hunk 1]
```diff
@@ -1,5 +1,9 @@
-export function selectIds (state, section, node) {
-  return (state.pagination[section] && state.pagination[section][node]) ? state.pagination[section][node].ids : []
+export function selectIds (state, section, node, compare) {
+  let ids = (state.pagination[section] && state.pagination[section][node]) ? state.pagination[section][node].ids : []
```
Comment (b5) [inline lib/selectors/pagination.js]: careful not to modify state here. the list of ids should _always_ be a new array.

**Review by b5 — CHANGES_REQUESTED** [review]

File: lib/selectors/pagination.js (hunk 1 above)
Comment (ramfox) [reply lib/selectors/pagination.js]: changed it!

**Review by b5 — APPROVED** [review]
🦊
