### PR TITLE
refactor(*): minor bug fixes

### LINKED ISSUE #409: On collection page: spinner should spin when datasets aren't loaded yet
Instead, it just says `no datasets` until the list of datasets comes back

### LINKED ISSUE #411: 0.6.0 minor issue punchlist
This is a collection of minor issues that I think are better tackled as a group b/c they're small. Ideally these can all be cleared out in a single PR

`Json.js`:
  * [x] `{,},[,]`characters are all white, which makes them invisible on a white background. we should adjust to accept a `color` prop or something so JSON rendered over a dark bg and light bg both work.

`Collection.js`:
  * [x] stats aren't hooked up
       note: dataset count and repo size hooked up. Counting commits is a bit more laborious right now, 
we would have to request the history of each dataset in the repo in order to count the history. Doesn't seem worth it from a performance perspective
  * [x] when datasets are loading, show the spinner (right now, it just says `no datasets`)

`Dataset:`
  * [x] let's move the viz option to be 2nd, just after Overview (if viz is defined)
  * [x] `add` button should turn into a loading button when we are adding the dataset
  * [x] `NavLinks` => link should be colored when active

`Editor.js`
  * [ ] ~contrast is a little low when blue is over grey~ moving this to tomorrow's punchlist
  * [x] default transform is out of date

### PR DESCRIPTION
**Pull request by ramfox**
closes #411
closes #409

### CODE REVIEW

File: lib/components/dataset/Dataset.js [hunk 1]
```diff
@@ -168,39 +168,6 @@ export default class Dataset extends Base {
     // adjust layout to include dataset header size:
     var layout = Object.assign({}, layoutMain, { height: layoutMain.height - 140 })
 
-    const datasetLinksAll = [
```
Comment (b5) [inline lib/components/dataset/Dataset.js:171]: nice, happy to see this move into DatasetHeader

File: lib/components/editor/EditTransform.js [hunk 2]
```diff
@@ -15,7 +15,7 @@ const blankTransform = {
 
 const starter = [
   '',
-  'def transform(ds):',
+  'def transform(ds, cxt):',
```
Comment (b5) [inline lib/components/editor/EditTransform.js]: This should be `ctx`, and let's lose the `return ds`, as it's no longer needed.

File: lib/containers/Collection.js [hunk 3]
```diff
@@ -19,7 +19,9 @@ const CollectionContainer = connect(
       noDatasets: selectNoDatasets(state, paginationSection, paginationNode),
       loading: selectIsFetching(state, paginationSection, paginationNode),
       nextPage: selectPageCount(state, paginationSection, paginationNode) + 1,
-      fetchedAll: selectFetchedAll(state, paginationSection, paginationNode)
+      fetchedAll: selectFetchedAll(state, paginationSection, paginationNode),
+      datasetsCount: selectSessionDatasetsCount(state),
```
Comment (b5) [inline lib/containers/Collection.js]: I think we should group these into a `stats` object that gets passed in as a prop. Can we get a new file `selectors/stats.js`:
```js
import { selectSessionDatasetsCount, selectSessionRepoSize } from './session'

export function selectStats(state) {
  return {
    datasetsCount: selectSessionDatasetsCount(state),
    repoSize: selectSessionRepoSize(state)
  }
}
```

We'd then change the container to pass around a stats object prop instead of individual stat properties.

That way as we grow we can keep adding stats here and not have to modify containers. In the long run I'm hoping to have stats be part of a dataset that describes a repo, and this'll help make that refactoring easier in the future.

File: lib/components/Collection.js [hunk 4]
```diff
@@ -66,10 +63,18 @@ class Collection extends Base {
...
-
+    const { message, error } = this.state
+    const { datasets, fetchedAll, datasetsCount, repoSize, loading } = this.props
+    const stats = [
+      {
+        title: 'datasets',
+        stat: datasetsCount
+      },
+      {
+        title: 'total repo size',
```
Comment (b5) [inline lib/components/Collection.js]: we chatted on slack, you pointed out that this is in fact just the summation of tip. We should rename this to "repo size (heads)"

**Review by b5 — COMMENTED** [review]
Looking good! a few bits & tweaks

**Review by b5 — APPROVED** [review]
LGTM
